TEMPLATEROOT = ../../C335-labs-Fall2019

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o f3d_led.o f3d_user_btn.o

# include common make file

include $(TEMPLATEROOT)/c335.mk


