TEMPLATEROOT = ../../C335-labs-Fall2019

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) 	main.o\
			f3d_user_btn.o \
			f3d_led.o \
			f3d_uart.o \
			f3d_gyro.o \
			f3d_delay.o \
			f3d_lcd_sd.o \
			glcdfont.o \
			stm32f30x_dma.o \
			stm32f30x_rcc.o \
			stm32f30x_tim.o \
			stm32f30x_gpio.o \
			stm32f30x_usart.o \
			stm32f30x_spi.o \
			newlib_stubs.o \
                        f3d_systick.o \
			queue.o\
                        stm32f30x_misc.o

# include common make file

include $(TEMPLATEROOT)/c335.mk


